import 'package:choco/core/assets/app_asset_registry.dart';

// Fallback cuando el manifiesto de Flutter no está disponible (p. ej. web).
// Actividades/destinos: ver también [kActividadImagenesPorDestino] y [kDestinoImagenesPorDestino].
const Set<String> kKnownBundledAssetPaths = {
  'assets/actividades/bogota/Atardecer Desde Mirador.jpg',
  'assets/actividades/bogota/Caminata Cultural Por La Candelaria.jpg',
  'assets/actividades/bogota/Cata De Café Colombiano.jpg',
  'assets/actividades/bogota/Chocolate Santafereño Con Queso.jpg',
  'assets/actividades/bogota/Ciclovía En Bogotá.jpg',
  'assets/actividades/bogota/Clase De Baile Latino.jpg',
  'assets/actividades/bogota/Clase De Cocina Colombiana.jpg',
  'assets/actividades/bogota/Escapada A Laguna Cercana.jpg',
  'assets/actividades/bogota/Experiencia De Café De Especialidad.jpg',
  'assets/actividades/bogota/La Candelaria.jpg',
  'assets/actividades/bogota/Monserrate.jpg',
  'assets/actividades/bogota/Museo Botero.jpg',
  'assets/actividades/bogota/Parque Simon Bolivar.jpg',
  'assets/actividades/bogota/Picnic En Parque Urbano.jpg',
  'assets/actividades/bogota/Recorrido De Arte Urbano.jpg',
  'assets/actividades/bogota/Recorrido Histórico Guiado.jpg',
  'assets/actividades/bogota/Ruta Fotográfica Por El Centro Histórico.jpg',
  'assets/actividades/bogota/Senderismo En Cerros Orientales.jpg',
  'assets/actividades/bogota/Teatro En Vivo.jpg',
  'assets/actividades/bogota/Tour De Comida Callejera.jpg',
  'assets/actividades/bogota/Tour De Museos.jpg',
  'assets/actividades/bogota/Tour Gastronómico Por La Candelaria.jpg',
  'assets/actividades/bogota/Tour Nocturno De Leyendas.jpg',
  'assets/actividades/bogota/Visita A Mercado Local.jpg',
  'assets/actividades/cali/Atardecer Desde Cristo Rey.jpg',
  'assets/actividades/cali/Bailar Salsa En Discoteca Local.jpg',
  'assets/actividades/cali/Baño En Río Pance.jpg',
  'assets/actividades/cali/Café De Especialidad.jpg',
  'assets/actividades/cali/Caminata Cultural Por San Antonio.jpg',
  'assets/actividades/cali/Clase De Baile Urbano.jpg',
  'assets/actividades/cali/Clase De Cocina Valluna.jpg',
  'assets/actividades/cali/Clase De Salsa Caleña.jpg',
  'assets/actividades/cali/Comida Típica En Galería Local.jpg',
  'assets/actividades/cali/Escapada Al Kilómetro 18.jpg',
  'assets/actividades/cali/Mercado Local Caleño.jpg',
  'assets/actividades/cali/Noche De Música En Vivo.jpg',
  'assets/actividades/cali/Picnic En Zona Verde.jpg',
  'assets/actividades/cali/Probar Lulada Y Cholado.jpg',
  'assets/actividades/cali/Recorrido De Murales.jpg',
  'assets/actividades/cali/Ruta De Miradores.jpg',
  'assets/actividades/cali/Ruta Gastronómica Valluna.jpg',
  'assets/actividades/cali/Senderismo En Los Farallones.jpg',
  'assets/actividades/cali/Sesión Fotográfica Urbana.jpg',
  'assets/actividades/cali/Show De Salsa En Vivo.jpg',
  'assets/actividades/cartagena/Atardecer En La Muralla.jpg',
  'assets/actividades/cartagena/Baile De Champeta.jpg',
  'assets/actividades/cartagena/Cena Frente Al Mar.jpg',
  'assets/actividades/cartagena/Clase De Baile Caribeño.jpg',
  'assets/actividades/cartagena/Clase De Cocina Cartagenera.jpg',
  'assets/actividades/cartagena/Cócteles En Terraza Histórica.jpg',
  'assets/actividades/cartagena/Degustación De Dulces Típicos.jpg',
  'assets/actividades/cartagena/Día De Playa En Barú.jpg',
  'assets/actividades/cartagena/Island Hopping.jpg',
  'assets/actividades/cartagena/Kayak En Manglares.jpg',
  'assets/actividades/cartagena/Paddleboard En El Mar.jpg',
  'assets/actividades/cartagena/Paseo En Barco Por La Bahía.jpg',
  'assets/actividades/cartagena/Paseo En Bicicleta Por Barrios Históricos.jpg',
  'assets/actividades/cartagena/Paseo En Lancha.jpg',
  'assets/actividades/cartagena/Recorrido Por Plazas Coloniales.jpg',
  'assets/actividades/cartagena/Ruta Fotográfica Colonial.jpg',
  'assets/actividades/cartagena/Snorkel En Islas.jpg',
  'assets/actividades/cartagena/Tour Cultural Por Getsemaní.jpg',
  'assets/actividades/cartagena/Tour Gastronómico Costeño.jpg',
  'assets/actividades/cartagena/Tour Nocturno De Leyendas.jpg',
  'assets/actividades/medellin/Atardecer Desde Terraza.jpg',
  'assets/actividades/medellin/Caminata Urbana Por Barrios Históricos.jpg',
  'assets/actividades/medellin/Clase De Café Especial.jpg',
  'assets/actividades/medellin/Clase De Cocina Antioqueña.jpg',
  'assets/actividades/medellin/Clase De Salsa.jpg',
  'assets/actividades/medellin/Escapada A Pueblo Cercano.jpg',
  'assets/actividades/medellin/Excursión A Cascadas.jpg',
  'assets/actividades/medellin/Experiencia Cultural Local.jpg',
  'assets/actividades/medellin/Mercado De Diseño Local.jpg',
  'assets/actividades/medellin/Parapente Cerca De Medellín.jpg',
  'assets/actividades/medellin/Picnic En Zona Verde.jpg',
  'assets/actividades/medellin/Recorrido De Grafiti.jpg',
  'assets/actividades/medellin/Recorrido Nocturno Por Provenza.jpg',
  'assets/actividades/medellin/Ruta Gastronómica Paisa.jpg',
  'assets/actividades/medellin/Senderismo En Parque Natural.jpg',
  'assets/actividades/medellin/Show De Música En Vivo.jpg',
  'assets/actividades/medellin/Tour De Transformación Social.jpg',
  'assets/actividades/medellin/Tour Fotográfico Urbano.jpg',
  'assets/actividades/medellin/Viaje En Metrocable.jpg',
  'assets/actividades/medellin/Visita A Finca Cafetera.jpg',
  'assets/choco/aprobacion.png',
  'assets/choco/choco_icon.png',
  'assets/choco/cielo.png',
  'assets/choco/confundido.png',
  'assets/choco/coqueto.png',
  'assets/choco/estresado.png',
  'assets/choco/felicidades.png',
  'assets/choco/grupo.png',
  'assets/choco/grupo_fondo.png',
  'assets/choco/hablando.png',
  'assets/choco/igotu.png',
  'assets/choco/itinerario.png',
  'assets/choco/logo.png',
  'assets/choco/maleta.jpeg',
  'assets/choco/mapa.jpeg',
  'assets/choco/mesa.png',
  'assets/choco/microfono.png',
  'assets/choco/pensando.png',
  'assets/choco/presupuesto.png',
  'assets/choco/ruta.png',
  'assets/choco/saludando.png',
  'assets/choco/sonrie.png',
  'assets/choco/usando_app.png',
  'assets/destinos/amazonas/f1.webp',
  'assets/destinos/amazonas/f10.jpg',
  'assets/destinos/amazonas/f12.png',
  'assets/destinos/amazonas/f2.webp',
  'assets/destinos/amazonas/f3.jpg',
  'assets/destinos/amazonas/f4.jpg',
  'assets/destinos/amazonas/f5.jpg',
  'assets/destinos/amazonas/f6.jpg',
  'assets/destinos/amazonas/f7.jpg',
  'assets/destinos/amazonas/f8.jpg',
  'assets/destinos/amazonas/f9.jpg',
  'assets/destinos/bogota/f1.jpg',
  'assets/destinos/bogota/f10.jpeg',
  'assets/destinos/bogota/f11.jpg',
  'assets/destinos/bogota/f12.jpg',
  'assets/destinos/bogota/f13.jpg',
  'assets/destinos/bogota/f2.avif',
  'assets/destinos/bogota/f3.jpg',
  'assets/destinos/bogota/f4.jpg',
  'assets/destinos/bogota/f5.jpg',
  'assets/destinos/bogota/f6.jpg',
  'assets/destinos/bogota/f7.jpg',
  'assets/destinos/bogota/f8.jpg',
  'assets/destinos/bogota/f9.jpg',
  'assets/destinos/cali/f1.avif',
  'assets/destinos/cali/f10.jpg',
  'assets/destinos/cali/f11.jpg',
  'assets/destinos/cali/f12.avif',
  'assets/destinos/cali/f13.jpg',
  'assets/destinos/cali/f14.jpg',
  'assets/destinos/cali/f2.jpg',
  'assets/destinos/cali/f3.jpg',
  'assets/destinos/cali/f4.jpg',
  'assets/destinos/cali/f5.webp',
  'assets/destinos/cali/f6.jpg',
  'assets/destinos/cali/f7.jpg',
  'assets/destinos/cali/f8.jpg',
  'assets/destinos/cali/f9.jpg',
  'assets/destinos/cartagena/f1.webp',
  'assets/destinos/cartagena/f10.jpg',
  'assets/destinos/cartagena/f11.jpg',
  'assets/destinos/cartagena/f12.jpg',
  'assets/destinos/cartagena/f2.webp',
  'assets/destinos/cartagena/f3.jpg',
  'assets/destinos/cartagena/f4.jpg',
  'assets/destinos/cartagena/f5.jpg',
  'assets/destinos/cartagena/f6.jpg',
  'assets/destinos/cartagena/f7.webp',
  'assets/destinos/cartagena/f8.avif',
  'assets/destinos/cartagena/f9.jpg',
  'assets/destinos/medellin/f1.jpg',
  'assets/destinos/medellin/f10.jpg',
  'assets/destinos/medellin/f11.webp',
  'assets/destinos/medellin/f12.webp',
  'assets/destinos/medellin/f13.webp',
  'assets/destinos/medellin/f14.jpeg',
  'assets/destinos/medellin/f14.jpg',
  'assets/destinos/medellin/f15.jpg',
  'assets/destinos/medellin/f16.jpg',
  'assets/destinos/medellin/f2.jpg',
  'assets/destinos/medellin/f3.jpg',
  'assets/destinos/medellin/f4.webp',
  'assets/destinos/medellin/f5.avif',
  'assets/destinos/medellin/f6.jpg',
  'assets/destinos/medellin/f7.jpg',
  'assets/destinos/medellin/f8.jpg',
  'assets/destinos/medellin/f9.webp',
  'assets/perfiles/hombre/p10.jpg',
  'assets/perfiles/hombre/p17.jpg',
  'assets/perfiles/hombre/p2.jpg',
  'assets/perfiles/hombre/p20.jpg',
  'assets/perfiles/hombre/p21.jpg',
  'assets/perfiles/hombre/p22.jpg',
  'assets/perfiles/hombre/p23.jpg',
  'assets/perfiles/hombre/p25.jpg',
  'assets/perfiles/hombre/p5.jpg',
  'assets/perfiles/hombre/p6.jpg',
  'assets/perfiles/mujer/p1.jpg',
  'assets/perfiles/mujer/p11.jpg',
  'assets/perfiles/mujer/p12.jpg',
  'assets/perfiles/mujer/p13.jpg',
  'assets/perfiles/mujer/p15.jpg',
  'assets/perfiles/mujer/p16.jpg',
  'assets/perfiles/mujer/p19.jpg',
  'assets/perfiles/mujer/p20.jpg',
  'assets/perfiles/mujer/p22.jpg',
  'assets/perfiles/mujer/p3.jpg',
  'assets/perfiles/mujer/p4.jpg',
  'assets/perfiles/mujer/p8.jpg',
  'assets/perfiles/placeholder.png',
};

bool _esImgBundled(String p) {
  final l = p.toLowerCase();
  return l.endsWith('.png') ||
      l.endsWith('.jpg') ||
      l.endsWith('.jpeg') ||
      l.endsWith('.webp') ||
      l.endsWith('.avif');
}

/// Carpetas bajo `assets/actividades/` (minúsculas, alineadas con destinoKey).
const Map<String, String> kCarpetaActividadesPorDestino = {
  'amazonas': '',
  'bogota': 'bogota',
  'cali': 'cali',
  'cartagena': 'cartagena',
  'medellin': 'medellin',
};

/// Imágenes de destino conocidas en el bundle (fallback sin manifiesto).
List<String> knownDestinoImagePathsForKey(String destinoKey) {
  final k = destinoKey.toLowerCase().trim();
  final reg = kDestinoImagenesPorDestino[k];
  if (reg != null && reg.isNotEmpty) return List<String>.from(reg);
  final pre = 'assets/destinos/$k/';
  return kKnownBundledAssetPaths.where((p) => p.startsWith(pre) && _esImgBundled(p)).toList()..sort();
}

/// Imágenes de actividades conocidas en el bundle.
List<String> knownActividadImagePathsForKey(String destinoKey) {
  final k = destinoKey.toLowerCase().trim();
  final reg = kActividadImagenesPorDestino[k];
  if (reg != null && reg.isNotEmpty) return List<String>.from(reg);
  final cap = kCarpetaActividadesPorDestino[k];
  if (cap == null || cap.isEmpty) return const [];
  final pre = 'assets/actividades/$cap/';
  return kKnownBundledAssetPaths.where((p) => p.startsWith(pre) && _esImgBundled(p)).toList()..sort();
}

/// Cualquier imagen de destino (último recurso visual, no Choco).
List<String> knownAnyDestinoImagePaths() {
  return kKnownBundledAssetPaths
      .where((p) => p.startsWith('assets/destinos/') && _esImgBundled(p))
      .toList()
    ..sort();
}
